### DISCUSSION TITLE
Inject default annotation(s)

### DISCUSSION THREAD

**Discussion by asimpleidea** [CloudNativeSDWAN/cnwan-operator#67] [Ideas]
I was thinking of a default annotation(s) injection feature that would run whenever the operator identifies a new service. This could help users avoid a lot of repetitive tasks, especially on a service mesh.

This is just a stub idea, please feel free to provide comments/feedback:

1a) you annotate a **namespace** as this:

```yaml
annotations:
- operator.cnwan.io/watch: enabled
- operator.cnwan.io/default-service-annotations: "traffic-profile=standard;this=that"
```

1b) This could even be a operator-settings level, like:

```yaml
... [other settings]
defaultAnnotations:
- namespace: my-namespace
   annotations:
   - traffic-profile=standard
   - this=that
```

Although I would prefer to *tag* namespaces directly for this, because a change would be detected immediately by the operator and for just that namespace and "feels like" directly modifying the namespace this way; while with `1b)` we would need to have a controller for `ConfigMaps` and have to parse it again to see what changed.

Lastly, I prefer to have namespace-scoped default annotations because I like that granularity, but nothing prevents us from just having a global `defaultAnnotations` to be inject on all watch-enabled namespaces.

2) Operator finds a new service (not necessarily a newly-created one, but even just one that wasn't watching before).
3) It finds that it doesn't have any of the defaults annotations I want on that service, and this is a clear misalignment from the desired state.
4) Op reconciles the state by writing those annotations to the service
5) Obviously the service is now changed => it will pass again through the operator, which will now see that it does have the default annotations and will not inject them, but instead...
6) ... the usual workflow happens
