### ISSUE TITLE
EKS: load balancer services need to be resolved prior to registering

### ISSUE THREAD

**Issue by asimpleidea** [CloudNativeSDWAN/cnwan-operator#137]
When creating a service of type `LoadBalancer` in EKS, this service is assigned a **hostname**. See example:

```yaml
[truncated for brevity...]
status:
  loadBalancer:
    ingress:
    - hostname: abc123674efg-648438329.us-west-1.elb.amazonaws.com
 ```

Obviously this won't be accepted by either Cloud Map or Service Directory, as they will only accept IP addresses, whether v4 or v6. So, in conclusion, whenever we see hostnames instead of IPs we need to resolve them in some way.

Specifically, for this scenario (EKS) I am thinking of these two ways of working:

- [x] Ask *CoreDNS* pods to resolve it for us
   - Benefit of this: will probably work for **any** managed k8s provider that work like this
   - Downside: don't really want to send DNS queries for this, API approach is preferable
- [ ] Study AWS SDK v2 to see if there is an endpoint that does this for us.
   - API based
   - Will only work for EKS.
 
Please provide ideas/comments/feedback if you think/know of an alternative way, as they are more than welcome!

Will keep posted.
